name: CustomMenu-BoilerPlate # TODO: 수정
main: net.starly.custommenu.boilerplate.BoilerPlate # TODO: 수정
author: Starly Team
website: https://starly.kr/

description: CustomMenu-BoilerPlate Plugin. # TODO: 수정

softdepend:
  - ST-Core
  - ST-CustomMenu

version: 1.0
api-version: 1.13

commands: