name: CM-ShiftF
main: net.starly.custommenu.shiftf.CMShiftF
author: Starly Team
website: https://starly.kr/

description: CM-ShiftF Plugin.

softdepend:
  - ST-Core
  - ST-CustomMenu

version: 1.0
api-version: 1.13

commands: